# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 20:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iban',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('[A-Z][A-Z]([0-9]*$)')]),
        ),
    ]
